using DevExpress.XtraBars;
using DevExpress.XtraGrid.Views.Grid;
using RAMSDBModel;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Windows.Forms;

namespace RAMSDB_WinForms
{
    public partial class TentativeRoadMaintenancePlan : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        private int _year;
        private Guid _roadID;
        private string _roadSurfaceType;
        List<UnpavedRoadUnitCost> unitCost = new List<UnpavedRoadUnitCost>();

        RAMSDBModel.RAMSDBEntities _context = new RAMSDBModel.RAMSDBEntities();

        public TentativeRoadMaintenancePlan(int Year, Guid RoadID)
        {
            InitializeComponent();

            _year = Year;
            _roadID = RoadID;
            _roadSurfaceType = _context.RoadsGISData.Where(c => c.RoadID == _roadID).Select(c => c.RoadSurfaceType.SurfaceTypeName).FirstOrDefault().ToString();

            InitBindings();
        }

        public TentativeRoadMaintenancePlan(int Year, Guid RoadID, string RoadSurfaceType)
        {
            InitializeComponent();

            _year = Year;
            _roadID = RoadID;
            _roadSurfaceType = RoadSurfaceType;

            InitBindings();
        }

        private void InitBindings()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext



            tentativeRoadMaintenancePlanBindingSource.DataSource = _context.UnpavedTentativeRoadMaintenancePlan.Include("RoadsGISData").Include("UnpavedCategoryofWork")
                                                                    .Where(c => c.RoadID == _roadID && c.Year == _year).ToList();
            categoryofWorkBindingSource.DataSource = _context.UnpavedCategoryofWork.ToList();

            unitCost = _context.UnpavedRoadUnitCost.ToList();

            lblRoadName.Text = "Road Name: " + _context.RoadsGISData.Where(c => c.RoadID == _roadID).Select(c => c.RoadOriginDestination).FirstOrDefault().ToString();


            lblSurfaceType.Text = "Road Surface Type: " + _roadSurfaceType;
            label2.Text = "Year: " + _year.ToString();

            //txtRoadID.Text ="Road Name: " + dbContext.RoadsGISData.Where(c => c.RoadID == _roadID).Select(c => c.RoadOriginDestination).FirstOrDefault().ToString();// x.Select(c => c.RoadsGISData.RoadOriginDestination).FirstOrDefault().ToString();// _roadID.ToString();
            //txtSurfaceType.Text ="Road Surface Type: "+ _roadSurfaceType;
            //txtYear.Text = "Year: " + _year.ToString();

            //    .Local.ToBindingList();

            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //dbContext.TentativeRoadMaintenancePlan.LoadAsync().ContinueWith(loadTask =>
            //{
            //    // Bind data to control when loading complete
            //    tentativeRoadMaintenancePlanBindingSource.DataSource = dbContext.TentativeRoadMaintenancePlan.Local.ToBindingList();
            //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void GridView_InitNewRow(object sender, DevExpress.XtraGrid.Views.Grid.InitNewRowEventArgs e)
        {
            gridView1.OptionsView.NewItemRowPosition = DevExpress.XtraGrid.Views.Grid.NewItemRowPosition.Top;

            //Handle the InitNewRow event to initialize newly added rows. To initialize row dcells use the SetRowCellValue method 

            DevExpress.XtraGrid.Views.Grid.GridView view = sender as DevExpress.XtraGrid.Views.Grid.GridView;
            view.SetRowCellValue(e.RowHandle, view.Columns["RoadID"], _roadID);
            view.SetRowCellValue(e.RowHandle, view.Columns["Year"], Convert.ToInt16(_year));


        }

        //private void barButtonItem1_ItemClick(object sender, ItemClickEventArgs e)
        //{


        //  _context.SaveChanges
        // //   {
        //  //      toastNotificationsManager1.ShowNotification(toastNotificationsManager1.Notifications[0]);
        // //   };

        //    // (gridControl1.DataSource as BindingList<TentativeRoadMaintenancePlan>).AddNew();
        //}

        private void gridControl1_Click(object sender, EventArgs e)
        {


        }

        private void GridView_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {

        }

        private void GridView_RowValidated(object sender, DevExpress.XtraGrid.Views.Base.ValidateRowEventArgs e)
        {
            GridView view = sender as GridView;
            if (e.Valid)
            {
                if (view.IsNewItemRow(e.RowHandle))
                {
                    RAMSDBModel.UnpavedTentativeRoadMaintenancePlan dw = (RAMSDBModel.UnpavedTentativeRoadMaintenancePlan)view.GetRow(e.RowHandle);
                    _context.UnpavedTentativeRoadMaintenancePlan.Add(dw);
                    _context.SaveChanges();
                }
                else
                {
                    _context.SaveChanges();
                }
            }


        }

        private void txtRoadID_TextChanged(object sender, EventArgs e)
        {

        }

        private void GridView_UnboundColumn(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs e)
        {
            GridView view = sender as GridView;
            if (view == null) return;


            int rowIndex = e.ListSourceRowIndex;
            int catID = (int)view.GetListSourceRowCellValue(rowIndex, "CatWorkID");


            if (unitCost.Where(c => c.CatWorkID == catID).Select(c => c.UnpavedUnitCost).FirstOrDefault() == null) return;
            decimal t = (decimal)unitCost.Where(c => c.CatWorkID == catID).Select(c => c.UnpavedUnitCost).FirstOrDefault();


            if (e.Column.FieldName != "UnitCost") return;
            if (e.IsGetData)
            {
                e.Value = t;
            }
        }

        private void Form_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (_context.ChangeTracker.HasChanges())
                _context.SaveChanges();

        }

        //private void barButtonItem2_ItemClick(object sender, ItemClickEventArgs e)
        //{
        //    if (gridView1.SelectedRowsCount > 0)
        //    {



        //        GridView view = gridView1 as GridView;



        //        int rowHandle = view.GetSelectedRows()[0];

        //        if (!view.IsGroupRow(rowHandle))
        //        {
        //            RAMSDBModel.UnpavedTentativeRoadMaintenancePlan dw = (RAMSDBModel.UnpavedTentativeRoadMaintenancePlan)view.GetRow(rowHandle);
        //            _context.UnpavedTentativeRoadMaintenancePlan.Remove(dw);
        //            _context.SaveChanges();
        //            gridView1.DeleteRow(rowHandle);

        //        }
        //    }
        //    else
        //    {
        //        MessageBox.Show("Please select a row from the table below first.");
        //    }
        //}

        private void bbiSave_ItemClick(object sender, ItemClickEventArgs e)
        {
            GridView view = gridView1 as GridView;

            view.PostEditor();

            view.UpdateCurrentRow();
        }

        private void bbiDelete_ItemClick(object sender, ItemClickEventArgs e)
        {
            if (gridView1.SelectedRowsCount > 0)
            {



                GridView view = gridView1 as GridView;



                int rowHandle = view.GetSelectedRows()[0];

                if (!view.IsGroupRow(rowHandle))
                {
                    RAMSDBModel.UnpavedTentativeRoadMaintenancePlan dw = (RAMSDBModel.UnpavedTentativeRoadMaintenancePlan)view.GetRow(rowHandle);
                    _context.UnpavedTentativeRoadMaintenancePlan.Remove(dw);
                    _context.SaveChanges();
                    view.DeleteRow(rowHandle);

                }
            }
            else
            {
                MessageBox.Show("Please select a row from the table below first.");
            }
        }
    }
}