//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 3/7/2022 4:13:26 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;

namespace RAMSDBModel
{
    [System.ComponentModel.DataAnnotations.Schema.Table("AnnualRoadWorkPlan", Schema = "dbo")]
    public partial class AnnualRoadWorkPlan : INotifyPropertyChanged
    {

        public AnnualRoadWorkPlan()
        {
            OnCreated();
        }

        #region Properties

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 0)]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public virtual int AnnualPlanID
        {
            get
            {
                return _AnnualPlanID;
            }
            set
            {
                if (_AnnualPlanID != value)
                {
                    _AnnualPlanID = value;
                    OnPropertyChanged("AnnualPlanID");
                }
            }
        }
        private int _AnnualPlanID;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "uniqueidentifier", Order = 1)]
        public virtual global::System.Guid RoadID
        {
            get
            {
                return _RoadID;
            }
            set
            {
                if (_RoadID != value)
                {
                    _RoadID = value;
                    OnPropertyChanged("RoadID");
                }
            }
        }
        private global::System.Guid _RoadID;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "smallint", Order = 2)]
        public virtual short FYearEC
        {
            get
            {
                return _FYearEC;
            }
            set
            {
                if (_FYearEC != value)
                {
                    _FYearEC = value;
                    OnPropertyChanged("FYearEC");
                }
            }
        }
        private short _FYearEC;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 3)]
        public virtual decimal? SectionLength
        {
            get
            {
                return _SectionLength;
            }
            set
            {
                if (_SectionLength != value)
                {
                    _SectionLength = value;
                    OnPropertyChanged("SectionLength");
                }
            }
        }
        private decimal? _SectionLength;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 4)]
        public virtual decimal? RoutineMaintenance
        {
            get
            {
                return _RoutineMaintenance;
            }
            set
            {
                if (_RoutineMaintenance != value)
                {
                    _RoutineMaintenance = value;
                    OnPropertyChanged("RoutineMaintenance");
                }
            }
        }
        private decimal? _RoutineMaintenance;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 5)]
        public virtual decimal? PeriodicMaintenance
        {
            get
            {
                return _PeriodicMaintenance;
            }
            set
            {
                if (_PeriodicMaintenance != value)
                {
                    _PeriodicMaintenance = value;
                    OnPropertyChanged("PeriodicMaintenance");
                }
            }
        }
        private decimal? _PeriodicMaintenance;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 6)]
        public virtual decimal? Rehabilitation
        {
            get
            {
                return _Rehabilitation;
            }
            set
            {
                if (_Rehabilitation != value)
                {
                    _Rehabilitation = value;
                    OnPropertyChanged("Rehabilitation");
                }
            }
        }
        private decimal? _Rehabilitation;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 7)]
        public virtual decimal? RoadBottleneck
        {
            get
            {
                return _RoadBottleneck;
            }
            set
            {
                if (_RoadBottleneck != value)
                {
                    _RoadBottleneck = value;
                    OnPropertyChanged("RoadBottleneck");
                }
            }
        }
        private decimal? _RoadBottleneck;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 8)]
        public virtual decimal? StructuralBottleneck
        {
            get
            {
                return _StructuralBottleneck;
            }
            set
            {
                if (_StructuralBottleneck != value)
                {
                    _StructuralBottleneck = value;
                    OnPropertyChanged("StructuralBottleneck");
                }
            }
        }
        private decimal? _StructuralBottleneck;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 9)]
        public virtual decimal? Qtr1Plan
        {
            get
            {
                return _Qtr1Plan;
            }
            set
            {
                if (_Qtr1Plan != value)
                {
                    _Qtr1Plan = value;
                    OnPropertyChanged("Qtr1Plan");
                }
            }
        }
        private decimal? _Qtr1Plan;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 10)]
        public virtual decimal? Qtr1Achievement
        {
            get
            {
                return _Qtr1Achievement;
            }
            set
            {
                if (_Qtr1Achievement != value)
                {
                    _Qtr1Achievement = value;
                    OnPropertyChanged("Qtr1Achievement");
                }
            }
        }
        private decimal? _Qtr1Achievement;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 11)]
        public virtual decimal? Qtr2Plan
        {
            get
            {
                return _Qtr2Plan;
            }
            set
            {
                if (_Qtr2Plan != value)
                {
                    _Qtr2Plan = value;
                    OnPropertyChanged("Qtr2Plan");
                }
            }
        }
        private decimal? _Qtr2Plan;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 12)]
        public virtual decimal? Qtr2Achievement
        {
            get
            {
                return _Qtr2Achievement;
            }
            set
            {
                if (_Qtr2Achievement != value)
                {
                    _Qtr2Achievement = value;
                    OnPropertyChanged("Qtr2Achievement");
                }
            }
        }
        private decimal? _Qtr2Achievement;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 13)]
        public virtual decimal? Qtr3Plan
        {
            get
            {
                return _Qtr3Plan;
            }
            set
            {
                if (_Qtr3Plan != value)
                {
                    _Qtr3Plan = value;
                    OnPropertyChanged("Qtr3Plan");
                }
            }
        }
        private decimal? _Qtr3Plan;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 14)]
        public virtual decimal? Qtr3Achievement
        {
            get
            {
                return _Qtr3Achievement;
            }
            set
            {
                if (_Qtr3Achievement != value)
                {
                    _Qtr3Achievement = value;
                    OnPropertyChanged("Qtr3Achievement");
                }
            }
        }
        private decimal? _Qtr3Achievement;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 15)]
        public virtual decimal? Qtr4Plan
        {
            get
            {
                return _Qtr4Plan;
            }
            set
            {
                if (_Qtr4Plan != value)
                {
                    _Qtr4Plan = value;
                    OnPropertyChanged("Qtr4Plan");
                }
            }
        }
        private decimal? _Qtr4Plan;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 16)]
        public virtual decimal? Qtr4Achievement
        {
            get
            {
                return _Qtr4Achievement;
            }
            set
            {
                if (_Qtr4Achievement != value)
                {
                    _Qtr4Achievement = value;
                    OnPropertyChanged("Qtr4Achievement");
                }
            }
        }
        private decimal? _Qtr4Achievement;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "text", Order = 17)]
        public virtual string Remarks
        {
            get
            {
                return _Remarks;
            }
            set
            {
                if (_Remarks != value)
                {
                    _Remarks = value;
                    OnPropertyChanged("Remarks");
                }
            }
        }
        private string _Remarks;

        #endregion

        #region Navigation Properties

        [System.ComponentModel.DataAnnotations.Schema.ForeignKey("RoadID")]
        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("AnnualRoadWorkPlans")]
        public virtual RoadsGISData RoadsGISData
        {
            get
            {
                return _RoadsGISData;
            }
            set
            {
                if (_RoadsGISData != value)
                {
                    _RoadsGISData = value;
                    OnPropertyChanged("RoadsGISData");
                }
            }
        }
        private RoadsGISData _RoadsGISData;

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
