//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 3/7/2022 4:13:26 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;

namespace RAMSDBModel
{
    [System.ComponentModel.DataAnnotations.Schema.Table("ContractPeformanceRoutineMaintenance", Schema = "dbo")]
    public partial class ContractPeformanceRoutineMaintenance : INotifyPropertyChanged
    {

        public ContractPeformanceRoutineMaintenance()
        {
            OnCreated();
        }

        #region Properties

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 0)]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public virtual int ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    _ID = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private int _ID;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 1)]
        public virtual int ContractRoutineID
        {
            get
            {
                return _ContractRoutineID;
            }
            set
            {
                if (_ContractRoutineID != value)
                {
                    _ContractRoutineID = value;
                    OnPropertyChanged("ContractRoutineID");
                }
            }
        }
        private int _ContractRoutineID;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "date", Order = 2)]
        public virtual global::System.DateTime? ProgressDate
        {
            get
            {
                return _ProgressDate;
            }
            set
            {
                if (_ProgressDate != value)
                {
                    _ProgressDate = value;
                    OnPropertyChanged("ProgressDate");
                }
            }
        }
        private global::System.DateTime? _ProgressDate;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 3)]
        public virtual decimal? TimeWorkedMonths
        {
            get
            {
                return _TimeWorkedMonths;
            }
            set
            {
                if (_TimeWorkedMonths != value)
                {
                    _TimeWorkedMonths = value;
                    OnPropertyChanged("TimeWorkedMonths");
                }
            }
        }
        private decimal? _TimeWorkedMonths;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 4)]
        public virtual decimal? ToDateWorkerDays
        {
            get
            {
                return _ToDateWorkerDays;
            }
            set
            {
                if (_ToDateWorkerDays != value)
                {
                    _ToDateWorkerDays = value;
                    OnPropertyChanged("ToDateWorkerDays");
                }
            }
        }
        private decimal? _ToDateWorkerDays;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 5)]
        public virtual decimal? TotalPaymentToDate
        {
            get
            {
                return _TotalPaymentToDate;
            }
            set
            {
                if (_TotalPaymentToDate != value)
                {
                    _TotalPaymentToDate = value;
                    OnPropertyChanged("TotalPaymentToDate");
                }
            }
        }
        private decimal? _TotalPaymentToDate;

        #endregion

        #region Navigation Properties

        [System.ComponentModel.DataAnnotations.Schema.ForeignKey("ContractRoutineID")]
        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("ContractPeformanceRoutineMaintenances")]
        public virtual ContractRoutineMaintenance ContractRoutineMaintenance
        {
            get
            {
                return _ContractRoutineMaintenance;
            }
            set
            {
                if (_ContractRoutineMaintenance != value)
                {
                    _ContractRoutineMaintenance = value;
                    OnPropertyChanged("ContractRoutineMaintenance");
                }
            }
        }
        private ContractRoutineMaintenance _ContractRoutineMaintenance;

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
