//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 3/9/2022 2:28:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;

namespace RAMSDBModel
{
    [System.ComponentModel.DataAnnotations.Schema.Table("ContractRoutineMaintenance", Schema = "dbo")]
    public partial class ContractRoutineMaintenance : INotifyPropertyChanged
    {

        public ContractRoutineMaintenance()
        {
            this.ContractPeformanceRoutineMaintenances = new ObservableListSource<ContractPeformanceRoutineMaintenance>();
            OnCreated();
        }

        #region Properties

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 0)]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public virtual int ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    _ID = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private int _ID;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 1)]
        public virtual string Region
        {
            get
            {
                return _Region;
            }
            set
            {
                if (_Region != value)
                {
                    _Region = value;
                    OnPropertyChanged("Region");
                }
            }
        }
        private string _Region;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 2)]
        public virtual string Woreda
        {
            get
            {
                return _Woreda;
            }
            set
            {
                if (_Woreda != value)
                {
                    _Woreda = value;
                    OnPropertyChanged("Woreda");
                }
            }
        }
        private string _Woreda;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 3)]
        public virtual string TypeOfWork
        {
            get
            {
                return _TypeOfWork;
            }
            set
            {
                if (_TypeOfWork != value)
                {
                    _TypeOfWork = value;
                    OnPropertyChanged("TypeOfWork");
                }
            }
        }
        private string _TypeOfWork;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 4)]
        public virtual string ContractNo
        {
            get
            {
                return _ContractNo;
            }
            set
            {
                if (_ContractNo != value)
                {
                    _ContractNo = value;
                    OnPropertyChanged("ContractNo");
                }
            }
        }
        private string _ContractNo;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar(max)", Order = 5)]
        public virtual string RoadSection
        {
            get
            {
                return _RoadSection;
            }
            set
            {
                if (_RoadSection != value)
                {
                    _RoadSection = value;
                    OnPropertyChanged("RoadSection");
                }
            }
        }
        private string _RoadSection;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 6)]
        public virtual decimal? SectionLength
        {
            get
            {
                return _SectionLength;
            }
            set
            {
                if (_SectionLength != value)
                {
                    _SectionLength = value;
                    OnPropertyChanged("SectionLength");
                }
            }
        }
        private decimal? _SectionLength;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 7)]
        public virtual string ContractorName
        {
            get
            {
                return _ContractorName;
            }
            set
            {
                if (_ContractorName != value)
                {
                    _ContractorName = value;
                    OnPropertyChanged("ContractorName");
                }
            }
        }
        private string _ContractorName;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 8)]
        public virtual decimal? ContractingEngEstimate
        {
            get
            {
                return _ContractingEngEstimate;
            }
            set
            {
                if (_ContractingEngEstimate != value)
                {
                    _ContractingEngEstimate = value;
                    OnPropertyChanged("ContractingEngEstimate");
                }
            }
        }
        private decimal? _ContractingEngEstimate;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "date", Order = 9)]
        public virtual global::System.DateTime? DateContractAwarded
        {
            get
            {
                return _DateContractAwarded;
            }
            set
            {
                if (_DateContractAwarded != value)
                {
                    _DateContractAwarded = value;
                    OnPropertyChanged("DateContractAwarded");
                }
            }
        }
        private global::System.DateTime? _DateContractAwarded;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 10)]
        public virtual decimal? ContractPrice
        {
            get
            {
                return _ContractPrice;
            }
            set
            {
                if (_ContractPrice != value)
                {
                    _ContractPrice = value;
                    OnPropertyChanged("ContractPrice");
                }
            }
        }
        private decimal? _ContractPrice;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 11)]
        public virtual decimal? AnnualWorkDays
        {
            get
            {
                return _AnnualWorkDays;
            }
            set
            {
                if (_AnnualWorkDays != value)
                {
                    _AnnualWorkDays = value;
                    OnPropertyChanged("AnnualWorkDays");
                }
            }
        }
        private decimal? _AnnualWorkDays;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 12)]
        public virtual decimal? RatePerWorkDays
        {
            get
            {
                return _RatePerWorkDays;
            }
            set
            {
                if (_RatePerWorkDays != value)
                {
                    _RatePerWorkDays = value;
                    OnPropertyChanged("RatePerWorkDays");
                }
            }
        }
        private decimal? _RatePerWorkDays;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "date", Order = 13)]
        public virtual global::System.DateTime? StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                if (_StartDate != value)
                {
                    _StartDate = value;
                    OnPropertyChanged("StartDate");
                }
            }
        }
        private global::System.DateTime? _StartDate;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "date", Order = 14)]
        public virtual global::System.DateTime? EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                if (_EndDate != value)
                {
                    _EndDate = value;
                    OnPropertyChanged("EndDate");
                }
            }
        }
        private global::System.DateTime? _EndDate;

        #endregion

        #region Navigation Properties

        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("ContractRoutineMaintenance")]
        public virtual ObservableListSource<ContractPeformanceRoutineMaintenance> ContractPeformanceRoutineMaintenances { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
