//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 3/9/2022 2:28:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;

namespace RAMSDBModel
{
    [System.ComponentModel.DataAnnotations.Schema.Table("MaintenanceBranch", Schema = "dbo")]
    public partial class MaintenanceBranch : INotifyPropertyChanged
    {

        public MaintenanceBranch()
        {
            this.RoadsGISDatas = new ObservableListSource<RoadsGISData>();
            OnCreated();
        }

        #region Properties

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "uniqueidentifier", Order = 0)]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public virtual global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    _ID = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private global::System.Guid _ID;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column("MaintenanceBranch", TypeName = "varchar", Order = 1)]
        public virtual string MaintenanceBranch1
        {
            get
            {
                return _MaintenanceBranch1;
            }
            set
            {
                if (_MaintenanceBranch1 != value)
                {
                    _MaintenanceBranch1 = value;
                    OnPropertyChanged("MaintenanceBranch1");
                }
            }
        }
        private string _MaintenanceBranch1;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 2)]
        public virtual string Region
        {
            get
            {
                return _Region;
            }
            set
            {
                if (_Region != value)
                {
                    _Region = value;
                    OnPropertyChanged("Region");
                }
            }
        }
        private string _Region;

        #endregion

        #region Navigation Properties

        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("MaintenanceBranch")]
        public virtual ObservableListSource<RoadsGISData> RoadsGISDatas { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
