//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 3/7/2022 4:13:26 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;

namespace RAMSDBModel
{
    [System.ComponentModel.DataAnnotations.Schema.Table("OfficeSupplyAdminCost", Schema = "dbo")]
    public partial class OfficeSupplyAdminCost : INotifyPropertyChanged
    {

        public OfficeSupplyAdminCost()
        {
            OnCreated();
        }

        #region Properties

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 0)]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public virtual int ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    _ID = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private int _ID;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 1)]
        public virtual string WorkPlanFiscalYear
        {
            get
            {
                return _WorkPlanFiscalYear;
            }
            set
            {
                if (_WorkPlanFiscalYear != value)
                {
                    _WorkPlanFiscalYear = value;
                    OnPropertyChanged("WorkPlanFiscalYear");
                }
            }
        }
        private string _WorkPlanFiscalYear;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 2)]
        public virtual string Region
        {
            get
            {
                return _Region;
            }
            set
            {
                if (_Region != value)
                {
                    _Region = value;
                    OnPropertyChanged("Region");
                }
            }
        }
        private string _Region;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 3)]
        public virtual string Woreda
        {
            get
            {
                return _Woreda;
            }
            set
            {
                if (_Woreda != value)
                {
                    _Woreda = value;
                    OnPropertyChanged("Woreda");
                }
            }
        }
        private string _Woreda;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 4)]
        public virtual string Item
        {
            get
            {
                return _Item;
            }
            set
            {
                if (_Item != value)
                {
                    _Item = value;
                    OnPropertyChanged("Item");
                }
            }
        }
        private string _Item;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 5)]
        public virtual string Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                if (_Quantity != value)
                {
                    _Quantity = value;
                    OnPropertyChanged("Quantity");
                }
            }
        }
        private string _Quantity;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 6)]
        public virtual decimal? UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                if (_UnitPrice != value)
                {
                    _UnitPrice = value;
                    OnPropertyChanged("UnitPrice");
                }
            }
        }
        private decimal? _UnitPrice;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 7)]
        public virtual decimal? TotalCost
        {
            get
            {
                return _TotalCost;
            }
            set
            {
                if (_TotalCost != value)
                {
                    _TotalCost = value;
                    OnPropertyChanged("TotalCost");
                }
            }
        }
        private decimal? _TotalCost;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 8)]
        public virtual decimal? SepMothlyExpense
        {
            get
            {
                return _SepMothlyExpense;
            }
            set
            {
                if (_SepMothlyExpense != value)
                {
                    _SepMothlyExpense = value;
                    OnPropertyChanged("SepMothlyExpense");
                }
            }
        }
        private decimal? _SepMothlyExpense;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 9)]
        public virtual decimal? OctMothlyExpense
        {
            get
            {
                return _OctMothlyExpense;
            }
            set
            {
                if (_OctMothlyExpense != value)
                {
                    _OctMothlyExpense = value;
                    OnPropertyChanged("OctMothlyExpense");
                }
            }
        }
        private decimal? _OctMothlyExpense;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 10)]
        public virtual decimal? NovMothlyExpense
        {
            get
            {
                return _NovMothlyExpense;
            }
            set
            {
                if (_NovMothlyExpense != value)
                {
                    _NovMothlyExpense = value;
                    OnPropertyChanged("NovMothlyExpense");
                }
            }
        }
        private decimal? _NovMothlyExpense;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 11)]
        public virtual decimal? DecMothlyExpense
        {
            get
            {
                return _DecMothlyExpense;
            }
            set
            {
                if (_DecMothlyExpense != value)
                {
                    _DecMothlyExpense = value;
                    OnPropertyChanged("DecMothlyExpense");
                }
            }
        }
        private decimal? _DecMothlyExpense;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 12)]
        public virtual decimal? JanMothlyExpense
        {
            get
            {
                return _JanMothlyExpense;
            }
            set
            {
                if (_JanMothlyExpense != value)
                {
                    _JanMothlyExpense = value;
                    OnPropertyChanged("JanMothlyExpense");
                }
            }
        }
        private decimal? _JanMothlyExpense;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 13)]
        public virtual decimal? FebMothlyExpense
        {
            get
            {
                return _FebMothlyExpense;
            }
            set
            {
                if (_FebMothlyExpense != value)
                {
                    _FebMothlyExpense = value;
                    OnPropertyChanged("FebMothlyExpense");
                }
            }
        }
        private decimal? _FebMothlyExpense;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 14)]
        public virtual decimal? MarMothlyExpense
        {
            get
            {
                return _MarMothlyExpense;
            }
            set
            {
                if (_MarMothlyExpense != value)
                {
                    _MarMothlyExpense = value;
                    OnPropertyChanged("MarMothlyExpense");
                }
            }
        }
        private decimal? _MarMothlyExpense;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 15)]
        public virtual decimal? AprMothlyExpense
        {
            get
            {
                return _AprMothlyExpense;
            }
            set
            {
                if (_AprMothlyExpense != value)
                {
                    _AprMothlyExpense = value;
                    OnPropertyChanged("AprMothlyExpense");
                }
            }
        }
        private decimal? _AprMothlyExpense;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 16)]
        public virtual decimal? MayMothlyExpense
        {
            get
            {
                return _MayMothlyExpense;
            }
            set
            {
                if (_MayMothlyExpense != value)
                {
                    _MayMothlyExpense = value;
                    OnPropertyChanged("MayMothlyExpense");
                }
            }
        }
        private decimal? _MayMothlyExpense;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 17)]
        public virtual decimal? JunMothlyExpense
        {
            get
            {
                return _JunMothlyExpense;
            }
            set
            {
                if (_JunMothlyExpense != value)
                {
                    _JunMothlyExpense = value;
                    OnPropertyChanged("JunMothlyExpense");
                }
            }
        }
        private decimal? _JunMothlyExpense;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 18)]
        public virtual decimal? JulMothlyExpense
        {
            get
            {
                return _JulMothlyExpense;
            }
            set
            {
                if (_JulMothlyExpense != value)
                {
                    _JulMothlyExpense = value;
                    OnPropertyChanged("JulMothlyExpense");
                }
            }
        }
        private decimal? _JulMothlyExpense;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 19)]
        public virtual decimal? AugMothlyExpense
        {
            get
            {
                return _AugMothlyExpense;
            }
            set
            {
                if (_AugMothlyExpense != value)
                {
                    _AugMothlyExpense = value;
                    OnPropertyChanged("AugMothlyExpense");
                }
            }
        }
        private decimal? _AugMothlyExpense;

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
