//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 3/7/2022 4:13:26 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;

namespace RAMSDBModel
{
    [System.ComponentModel.DataAnnotations.Schema.Table("RoadWorkFunding", Schema = "dbo")]
    public partial class RoadWorkFunding : INotifyPropertyChanged
    {

        public RoadWorkFunding()
        {
            OnCreated();
        }

        #region Properties

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 0)]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public virtual int ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    _ID = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private int _ID;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 1)]
        public virtual string WorkPlanFiscalYear
        {
            get
            {
                return _WorkPlanFiscalYear;
            }
            set
            {
                if (_WorkPlanFiscalYear != value)
                {
                    _WorkPlanFiscalYear = value;
                    OnPropertyChanged("WorkPlanFiscalYear");
                }
            }
        }
        private string _WorkPlanFiscalYear;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 2)]
        public virtual string Region
        {
            get
            {
                return _Region;
            }
            set
            {
                if (_Region != value)
                {
                    _Region = value;
                    OnPropertyChanged("Region");
                }
            }
        }
        private string _Region;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 3)]
        public virtual string Woreda
        {
            get
            {
                return _Woreda;
            }
            set
            {
                if (_Woreda != value)
                {
                    _Woreda = value;
                    OnPropertyChanged("Woreda");
                }
            }
        }
        private string _Woreda;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 4)]
        public virtual string FundingSource
        {
            get
            {
                return _FundingSource;
            }
            set
            {
                if (_FundingSource != value)
                {
                    _FundingSource = value;
                    OnPropertyChanged("FundingSource");
                }
            }
        }
        private string _FundingSource;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 5)]
        public virtual decimal? RoadLength
        {
            get
            {
                return _RoadLength;
            }
            set
            {
                if (_RoadLength != value)
                {
                    _RoadLength = value;
                    OnPropertyChanged("RoadLength");
                }
            }
        }
        private decimal? _RoadLength;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 6)]
        public virtual decimal? InterventionCostRM
        {
            get
            {
                return _InterventionCostRM;
            }
            set
            {
                if (_InterventionCostRM != value)
                {
                    _InterventionCostRM = value;
                    OnPropertyChanged("InterventionCostRM");
                }
            }
        }
        private decimal? _InterventionCostRM;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 7)]
        public virtual decimal? InterventionCostPM
        {
            get
            {
                return _InterventionCostPM;
            }
            set
            {
                if (_InterventionCostPM != value)
                {
                    _InterventionCostPM = value;
                    OnPropertyChanged("InterventionCostPM");
                }
            }
        }
        private decimal? _InterventionCostPM;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 8)]
        public virtual decimal? InterventionCostRehabilitation
        {
            get
            {
                return _InterventionCostRehabilitation;
            }
            set
            {
                if (_InterventionCostRehabilitation != value)
                {
                    _InterventionCostRehabilitation = value;
                    OnPropertyChanged("InterventionCostRehabilitation");
                }
            }
        }
        private decimal? _InterventionCostRehabilitation;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 9)]
        public virtual decimal? InterventionCostRoadBottleneck
        {
            get
            {
                return _InterventionCostRoadBottleneck;
            }
            set
            {
                if (_InterventionCostRoadBottleneck != value)
                {
                    _InterventionCostRoadBottleneck = value;
                    OnPropertyChanged("InterventionCostRoadBottleneck");
                }
            }
        }
        private decimal? _InterventionCostRoadBottleneck;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 10)]
        public virtual decimal? InterventionCostStructureBottleneck
        {
            get
            {
                return _InterventionCostStructureBottleneck;
            }
            set
            {
                if (_InterventionCostStructureBottleneck != value)
                {
                    _InterventionCostStructureBottleneck = value;
                    OnPropertyChanged("InterventionCostStructureBottleneck");
                }
            }
        }
        private decimal? _InterventionCostStructureBottleneck;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "decimal", Order = 11)]
        public virtual decimal? YearCost
        {
            get
            {
                return _YearCost;
            }
            set
            {
                if (_YearCost != value)
                {
                    _YearCost = value;
                    OnPropertyChanged("YearCost");
                }
            }
        }
        private decimal? _YearCost;

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
