//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 3/7/2022 4:13:26 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;

namespace RAMSDBModel
{
    [System.ComponentModel.DataAnnotations.Schema.Table("UnpavedCategoryofWork", Schema = "dbo")]
    public partial class UnpavedCategoryofWork : INotifyPropertyChanged
    {

        public UnpavedCategoryofWork()
        {
            this.UnpavedRoadUnitCosts = new ObservableListSource<UnpavedRoadUnitCost>();
            this.UnpavedTentativeRoadMaintenancePlans = new ObservableListSource<UnpavedTentativeRoadMaintenancePlan>();
            OnCreated();
        }

        #region Properties

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 0)]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public virtual int CatWorkID
        {
            get
            {
                return _CatWorkID;
            }
            set
            {
                if (_CatWorkID != value)
                {
                    _CatWorkID = value;
                    OnPropertyChanged("CatWorkID");
                }
            }
        }
        private int _CatWorkID;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 1)]
        public virtual string CategoryofWorkName
        {
            get
            {
                return _CategoryofWorkName;
            }
            set
            {
                if (_CategoryofWorkName != value)
                {
                    _CategoryofWorkName = value;
                    OnPropertyChanged("CategoryofWorkName");
                }
            }
        }
        private string _CategoryofWorkName;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 2)]
        public virtual string WorkCode
        {
            get
            {
                return _WorkCode;
            }
            set
            {
                if (_WorkCode != value)
                {
                    _WorkCode = value;
                    OnPropertyChanged("WorkCode");
                }
            }
        }
        private string _WorkCode;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar(max)", Order = 3)]
        public virtual string WorkDescription
        {
            get
            {
                return _WorkDescription;
            }
            set
            {
                if (_WorkDescription != value)
                {
                    _WorkDescription = value;
                    OnPropertyChanged("WorkDescription");
                }
            }
        }
        private string _WorkDescription;

        #endregion

        #region Navigation Properties

        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("UnpavedCategoryofWork")]
        public virtual ObservableListSource<UnpavedRoadUnitCost> UnpavedRoadUnitCosts { get; set; }
        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("UnpavedCategoryofWork")]
        public virtual ObservableListSource<UnpavedTentativeRoadMaintenancePlan> UnpavedTentativeRoadMaintenancePlans { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
